---

- include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'
  tags: package

- include_tasks: redhat.yml
  when: ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
  tags: package

- name: Create netbox group 
  group:
    name: "{{ netbox_group }}"
    state: present 

- name: Create netbox user
  user:
    name: "{{ netbox_user  }}"
    group: "{{ netbox_group }}"	    
    state: present 

- name: Ensure Postgres database exists (via TCP)
  postgresql_db:
    name: "{{ netbox_database }}"
    login_host: "{{ netbox_database_host }}"
    port: "{{ netbox_database_port }}"
    login_user: "{{ netbox_database_user }}"
    login_password: "{{ netbox_database_password }}"
  when:
    - netbox_database_socket is not defined
    - netbox_database_host is defined

- import_tasks: deploy_netbox.yml

- name: Copy systemd files
  copy:
    src: "/opt/netbox/contrib/{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    remote_src: yes
  loop:
    - netbox
    - netbox-rq

- name: just force systemd to reread configs
  systemd: daemon_reload=yes

- name: Install virtualenv
  pip:
    name: virtualenv

- name: Start and enable services 
  service:
    name: "{{ item }}"
    state: started 
    enabled: yes
  loop:
    - netbox
    - netbox-rq



