---

- name: Install ldap requirements
  pip:
    name:
      - ldap
      - django_auth_ldap
    virtualenv: "{{ netbox_virtualenv_path }}"
    virtualenv_command: "{{ netbox_python_binary }} -m venv"
  become: true
  become_user: "{{ netbox_user }}"

