---

- name: restart netbox
  service:
    name: netbox
    state: restarted
    enabled: true

- name: restart netbox rqworker
  service:
    name: netbox-rqworker
    state: restarted
    enabled: true

- name: restart nginx
  service:
    name: nginx
    state: restarted 
