---
- name: Manage postgresql
  hosts: netbox_db
  user: freis
  become: true
  vars_files:
    - ./netbox.yml
  tasks:
    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"

    - name: "Grant db user access to app db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all

    - name: "Allow md5 connection for the db user"
      postgresql_pg_hba:
        dest: "~/data/pg_hba.conf"
        contype: host
        databases: all
        method: md5
        users: "{{ db_user }}"
        create: true
      notify: restart postgres

  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
