---
- include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'
  tags: package

- include_tasks: redhat.yml
  when: ansible_facts['distribution'] == 'RedHat' or ansible_facts['distribution'] == 'CentOS'
  tags: package

- name: "Start and enable services"
  service: 
    name: "{{ pg_svc }}"
    state: started 
    enabled: yes
